### ISSUE TITLE
Set parameters works :)

### ISSUE THREAD

**Issue by zoernert** [tomquist/solix2mqtt#3]
First of all I would like to thank you for exploring all the endpoints. Maybe you could give me a small hint where you found them. I just checked that setting parameters (timetable "Familienladung") works fine, so that a smart load following is straight forward. In my case, I use the mains meter to check my actual load and adopt a single range with some small changes every 15 minutes. As I have a real roof-top PV in addition, it is more to avoid the Anker Solix to be drained  in cases I already have more electricity than self consumption requires.

As you write that, you do not have a E1600 anymore. Do you like to hand over your project? 

Final: You might give me a hint where you found the API endpoints?

**Comment by tomquist** [comment]
Thanks for the feedback. The way I found these endpoints was by using a MITM proxy while using Anker‘s Android app. The App was built with Flutter so I had to patch it using a tool called [ReFlutter](https://github.com/ptswarm/reFlutter) in order to bypass SSL verification.

As of your questions around handing over the project: I’m happy to accept contributions and add maintainers to the project in case anyone is interested. I still have an Anker account with a connected Solarbank, it just shows as offline (as I sent my Solarbank back) so I also might be able to test a couple of things if necessary.
